# Generated by Django 6.0.2 on 2026-04-22 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale', '0001_initial'),
        ('utilities', '0016_alter_recipeitem_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_no', models.CharField(max_length=50, unique=True)),
                ('planned_qty', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.machine')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.saleorder')),
            ],
        ),
    ]
