# Generated by Django 6.0.2 on 2026-04-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplan',
            name='status',
            field=models.CharField(default='Open', max_length=20),
        ),
    ]
