# Generated by Django 6.0.2 on 2026-05-12 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_workorder_workorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionplan',
            name='sale_order',
        ),
        migrations.AddField(
            model_name='productionplan',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.workorder'),
        ),
    ]
