# Generated by Django on 2026-05-15 00:00

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_remove_productionplan_sale_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=50, unique=True)),
                ('inspected_at', models.DateTimeField(auto_now_add=True)),
                ('four_point_faults', models.IntegerField(default=0)),
                ('press_hole', models.IntegerField(default=0)),
                ('rafu', models.IntegerField(default=0)),
                ('needle_break', models.IntegerField(default=0)),
                ('double_kunda', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='production.productionroll')),
            ],
        ),
    ]
