# Generated by Django 6.0.2 on 2026-05-21 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_qualityentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=50, unique=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('gsm', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pass', 'Pass'), ('Hold', 'Hold'), ('Reject', 'Reject')], default='Pass', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quality_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finishing_entry', to='production.qualityentry')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishing_entries', to='production.productionroll')),
            ],
        ),
    ]
