# Generated by Django 6.0.2 on 2026-04-05 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('utilities', '0005_alter_department_department_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpr',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.department'),
        ),
    ]
