# Generated by Django 6.0.2 on 2026-04-15 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
        ('utilities', '0012_alter_rack_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='grn',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='rack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.rack'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
