# Generated by Django 6.0.2 on 2026-04-16 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilities', '0012_alter_rack_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_order_no', models.CharField(max_length=50, unique=True)),
                ('so_date', models.DateField()),
                ('customer_po_no', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_po_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('order_qty', models.FloatField()),
                ('fabric_width_type', models.CharField(max_length=20)),
                ('fabric_width', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('finishing_process', models.CharField(max_length=200)),
                ('cut_level', models.CharField(max_length=10)),
                ('sample_status', models.CharField(max_length=10)),
                ('received_by', models.CharField(max_length=50)),
                ('shipment_location', models.CharField(max_length=200)),
                ('delivery_date', models.DateField()),
                ('order_type', models.CharField(max_length=50)),
                ('payment_term', models.CharField(max_length=50)),
                ('price_order', models.FloatField()),
                ('rate', models.FloatField()),
                ('currency_type', models.CharField(max_length=10)),
                ('currency_rate', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.product')),
                ('yarn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.yarn')),
            ],
        ),
    ]
