# Generated by Django 6.0.2 on 2026-05-11 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_saleorder_status'),
        ('utilities', '0017_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorder',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='saleorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.customer'),
        ),
    ]
