# Generated by Django 6.0.2 on 2026-05-11 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_remove_saleorder_customer_name_saleorder_customer'),
        ('utilities', '0017_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.customer'),
        ),
    ]
