# Generated by Django 6.0.2 on 2026-05-11 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_alter_saleorder_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleorder',
            old_name='delivery_date',
            new_name='end_delivery_date',
        ),
        migrations.AddField(
            model_name='saleorder',
            name='start_delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
