# Generated by Django 6.0.2 on 2026-05-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_rename_delivery_date_saleorder_end_delivery_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleorder',
            old_name='currency_rate',
            new_name='rate_per_unit',
        ),
        migrations.RenameField(
            model_name='saleorder',
            old_name='price_order',
            new_name='total_price_order',
        ),
        migrations.RemoveField(
            model_name='saleorder',
            name='currency_type',
        ),
        migrations.RemoveField(
            model_name='saleorder',
            name='cut_level',
        ),
        migrations.RemoveField(
            model_name='saleorder',
            name='rate',
        ),
    ]
