# Generated by Django 6.0.2 on 2026-05-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_rename_currency_rate_saleorder_rate_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='rate_per_unit',
            field=models.CharField(),
        ),
    ]
