# Generated by Django 6.0.2 on 2026-05-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_alter_saleorder_rate_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='rate_per_unit',
            field=models.FloatField(),
        ),
    ]
