# Generated by Django 6.0.2 on 2026-04-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0004_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('Production', 'Production'), ('Stock', 'Stock')], max_length=20),
        ),
    ]
