# Generated by Django 6.0.2 on 2026-04-14 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0007_alter_product_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='utilities.product')),
                ('yarn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.yarn')),
            ],
        ),
    ]
