# Generated by Django 6.0.2 on 2026-04-14 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0009_recipe_recipeitem_delete_productitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.product'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='yarn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.yarn'),
        ),
    ]
