# Generated by Django 6.0.2 on 2026-04-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0010_recipeitem_product_alter_recipeitem_yarn'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rack',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rack',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together={('rack_no', 'department')},
        ),
    ]
