# Generated by Django 6.0.2 on 2026-04-15 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0011_rack_date_rack_department_alter_rack_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.department'),
        ),
    ]
