# Generated by Django 6.0.2 on 2026-04-17 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0012_alter_rack_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=50, unique=True)),
                ('machine_name', models.CharField(max_length=100)),
                ('gauge', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('machine_brand', models.CharField(max_length=100)),
                ('feeders', models.IntegerField()),
                ('structure', models.CharField(max_length=100)),
                ('capacity_per_day', models.IntegerField()),
                ('machine_group', models.CharField(choices=[('Flat Knit', 'Flat Knit'), ('Circular', 'Circular'), ('Wrist', 'Wrist')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
