# Generated by Django 6.0.2 on 2026-04-19 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0013_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.department'),
        ),
        migrations.AlterUniqueTogether(
            name='machine',
            unique_together={('machine_code', 'department')},
        ),
    ]
