# Generated by Django 6.0.2 on 2026-04-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0014_machine_department_alter_machine_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='finishing_process',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
