# Generated by Django 6.0.2 on 2026-04-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0015_recipe_finishing_process_alter_department_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeitem',
            unique_together=set(),
        ),
    ]
